import { ArrowDownRight, ArrowUpRight, Code2, Download, Mail, MapPin, Phone, Terminal } from "lucide-react";
import { SnakeGame } from "@/components/snake-game";

const projects = [
  { number: "01", title: "Portfolio personnel", description: "Création et amélioration de mon propre site internet pour apprendre à créer une interface, organiser du contenu et améliorer progressivement une application web.", tags: ["HTML", "CSS", "JavaScript"], tone: "mint" },
  { number: "02", title: "Bot Discord", description: "Création d’un bot Discord avec différentes fonctionnalités automatisées pour découvrir les API, la logique et la communication avec un service externe.", tags: ["Programmation", "API", "Automatisation"], tone: "sand" },
  { number: "03", title: "Projets Python", description: "Petits programmes réalisés pour apprendre progressivement les variables, les fonctions, la logique et la gestion de fichiers.", tags: ["Python", "Logique", "Fonctions"], tone: "blue" },
  { number: "04", title: "Linux & réseaux", description: "Découverte de Linux, des systèmes informatiques et des bases du fonctionnement d’un réseau, avec documentation de mes expérimentations.", tags: ["Linux", "Systèmes", "Réseaux"], tone: "mint" },
  { number: "05", title: "Programmation Roblox", description: "Première découverte de la programmation avec Roblox Studio, Luau, les scripts et la création de jeux.", tags: ["Luau", "Scripts", "Création"], tone: "sand" },
];
const learningTopics = [
  { title: "Programmation", detail: "Python · JavaScript · Luau · HTML · CSS" },
  { title: "Informatique", detail: "Systèmes · réseaux · dépannage · Linux" },
  { title: "Création", detail: "Sites web · petits programmes · jeux · automatisation" },
  { title: "Langues", detail: "Français · Anglais" },
];

export default function Home() {
  return (
    <main>
      <header className="site-header"><a className="wordmark" href="#top" aria-label="Accueil du CV de Roméo Paris">RP<span>.</span></a><nav className="site-nav" aria-label="Navigation principale"><a href="#recherche">Recherche</a><a href="#projets">Projets</a><a href="#contact">Contact</a></nav><a className="header-availability" href="mailto:Romeo.paris321@gmail.com"><span /> À la recherche d’un apprentissage</a></header>
      <section className="hero section-frame" id="top"><div className="hero-copy"><p className="eyebrow">Futur apprenti informaticien · 16 ans · Bulle, Fribourg</p><h1>Roméo Paris, <em>j’apprends et je construis.</em></h1><p className="hero-summary">Passionné par l’informatique et curieux de comprendre comment les technologies fonctionnent, je développe actuellement mes compétences à travers des projets personnels et différentes expériences professionnelles.<br /><br />Je souhaite intégrer un <strong>CFC d’informaticien en septembre 2027</strong> afin de transformer ma passion pour l’informatique en véritable métier.</p><div className="hero-actions"><a className="primary-link" href="#projets">Voir mes projets <ArrowDownRight size={17} /></a><a className="text-link" href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf">Télécharger mon CV <Download size={16} /></a></div></div><div className="hero-proof" aria-label="Objectif professionnel"><div className="proof-mark"><Terminal size={22} /></div><p className="proof-label">Ma direction</p><p className="proof-title">Apprendre.<br />Construire.<br />Progresser.</p><p className="proof-detail">Je cherche une place d’apprentissage CFC d’informaticien pour septembre 2027 dans la région de Fribourg et alentours.</p><div className="proof-footer"><span>16 ans</span><span>Bulle · Suisse</span></div></div></section>
      <section className="signal-strip" aria-label="Résumé du profil"><div><span className="signal-number">2027</span><span>objectif : CFC Informatique</span></div><div><span className="signal-number">💻</span><span>projets personnels</span></div><div><span className="signal-number">🚀</span><span>apprentissage autonome</span></div></section>
      <section className="section-frame focus-section" id="recherche"><div className="about-grid"><div><p className="eyebrow">Ce que je recherche</p><h2>Mon prochain défi : l’informatique.</h2></div><div className="about-copy"><p>Je recherche une <strong>place d’apprentissage CFC d’informaticien pour septembre 2027</strong>, dans la région de Fribourg et alentours.</p><p>Je suis particulièrement intéressé par le développement d’applications, l’informatique et les systèmes, les réseaux, la programmation, le support et la résolution de problèmes, ainsi que l’automatisation et les nouvelles technologies.</p><p>Je suis encore au début de mon parcours informatique, mais j’aime apprendre par moi-même et surtout <strong>transformer ce que j’apprends en projets concrets.</strong></p></div></div></section>
      <section className="section-frame work-section" id="projets"><div className="section-heading"><div><p className="eyebrow">Mes projets</p><h2>J’apprends en construisant.</h2></div><p className="section-aside">Des projets personnels pour comprendre l’informatique en pratique.</p></div><div className="project-grid">{projects.map((project) => <article className={`project-card ${project.tone}`} key={project.number}><div className="project-card-top"><span>{project.number}</span><ArrowUpRight size={19} /></div><div><h3>{project.title}</h3><p>{project.description}</p></div><div className="tag-row">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
      <section className="section-frame learning-section" id="apprentissage"><div className="section-heading"><div><p className="eyebrow">Ce que j’aime apprendre</p><h2>Des bases que je transforme en projets.</h2></div><p className="section-aside">Je progresse en testant, documentant et recommençant.</p></div><div className="learning-grid">{learningTopics.map((topic, index) => <article className="learning-card" key={topic.title}><p className="learning-number">0{index + 1}</p><h3>{topic.title}</h3><p>{topic.detail}</p></article>)}</div></section>
      <section className="section-frame about-section" id="parcours"><div className="about-grid"><div><p className="eyebrow">Mon parcours</p><h2>Des expériences différentes qui m’ont appris à m’adapter.</h2></div><div className="about-copy"><h3>Formation professionnelle</h3><p>J’ai commencé une formation professionnelle dans le domaine de l’électronique. Cette expérience m’a permis de découvrir le monde professionnel, le travail en équipe et l’importance de la précision et de la rigueur.</p><p>Même si je souhaite aujourd’hui m’orienter vers l’informatique, cette expérience fait partie de mon parcours et m’a permis de mieux comprendre le domaine professionnel.</p><h3>Stage à l’HFR Fribourg</h3><p>Une première expérience dans le monde professionnel, où j’ai découvert les exigences d’un environnement de travail et développé mon sens de l’organisation et des responsabilités.</p><h3>FutureKids Fribourg</h3><p>Une première découverte de la programmation et de la création numérique, qui a renforcé mon intérêt pour la programmation.</p></div></div></section>
      <section className="section-frame about-section about-profile" id="apropos"><div className="about-grid"><div><p className="eyebrow">À propos de moi</p><h2>Curieux, motivé et toujours prêt à apprendre.</h2></div><div className="about-copy"><p>Je suis quelqu’un de sociable, curieux et persévérant. Quand quelque chose m’intéresse, j’aime comprendre <strong>comment ça fonctionne</strong>, essayer par moi-même et chercher une solution lorsque je rencontre un problème.</p><p>L’informatique m’attire particulièrement parce qu’elle permet de partir d’une idée et de la transformer en quelque chose de concret.</p><p>Je ne prétends pas déjà tout connaître.</p><p><strong>Mon objectif est justement d’apprendre.</strong></p></div></div></section>
      <section className="section-frame github-section" id="github"><div className="github-card"><div><p className="eyebrow">Mon GitHub</p><h2>Mes projets, mon évolution.</h2><p>Je publie progressivement mes projets et mes expérimentations afin de montrer ce que j’apprends et comment mes compétences évoluent.</p></div><div className="github-action"><Code2 size={28} /><span className="text-link text-link-disabled">Voir mon GitHub <ArrowUpRight size={16} /></span><small>Lien à ajouter</small></div></div></section>
      <section className="section-frame cv-section" id="cv"><div className="cv-card"><div><p className="eyebrow">CV</p><h2>Vous souhaitez en savoir plus sur mon parcours ?</h2></div><a className="primary-link" href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf">Télécharger mon CV <Download size={17} /></a></div></section>
      <section className="section-frame game-section" id="jeu"><div className="game-intro"><p className="eyebrow">Un projet personnel</p><h2>Une petite démonstration de logique.</h2><p>Le Snake montre mon intérêt pour la programmation et les interactions. Utilise les flèches ou les touches ZQSD pour jouer.</p><a className="text-link" href="#contact">Parler de mon profil <ArrowUpRight size={16} /></a></div><SnakeGame /></section>
      <section className="contact-section" id="contact"><div className="section-frame contact-inner"><div><p className="eyebrow">Contact</p><h2>Vous recherchez un apprenti motivé ?</h2><p className="contact-copy">Je serais heureux d’échanger avec une entreprise au sujet d’une place d’apprentissage CFC d’informaticien pour septembre 2027, d’un stage ou d’une journée de découverte.</p></div><div className="contact-actions"><a className="primary-link" href="mailto:Romeo.paris321@gmail.com"><Mail size={17} /> Me contacter par e-mail</a><a className="contact-email" href="mailto:Romeo.paris321@gmail.com">Romeo.paris321@gmail.com <ArrowUpRight size={16} /></a><a className="contact-email" href="tel:+41766151828"><Phone size={16} /> +41 76 615 18 28</a><p className="location"><MapPin size={15} /> Bulle · Fribourg · Suisse</p></div></div></section>
      <footer className="site-footer section-frame"><span>© 2026 Roméo Paris</span><span>CV en ligne</span><a href="#top">Retour en haut <ArrowUpRight size={14} /></a></footer>
    </main>
  );
}
