import { ArrowDownRight, ArrowUpRight, Download, Mail, MapPin, Quote, Terminal } from "lucide-react";
import { SnakeGame } from "@/components/snake-game";

const projects = [
  { number: "01", title: "Operations command center", description: "A calmer daily view for a distributed support team, with faster handoffs and fewer blind spots.", tags: ["Next.js", "TypeScript", "Systems design"], tone: "mint" },
  { number: "02", title: "Portfolio system", description: "A flexible publishing surface that keeps case studies readable, scannable, and easy to update.", tags: ["React", "Content modeling", "Accessibility"], tone: "sand" },
  { number: "03", title: "Snake / playable demo", description: "A small browser game built to show interaction details, responsive controls, and a sense of play.", tags: ["React state", "Keyboard input", "Game loop"], tone: "blue" },
];
const skills = ["TypeScript", "React", "Next.js", "Node.js", "SQL", "Design systems", "Testing", "Accessibility"];
const endorsements = [
  { quote: "Add a specific recommendation about how Alex improved a product, process, or team outcome.", name: "Your colleague’s name", role: "Role · Company" },
  { quote: "Add a second point of view from a manager, collaborator, or client who can speak to the work.", name: "Your former manager’s name", role: "Role · Company" },
];

export default function Home() {
  return (
    <main>
      <header className="site-header"><a className="wordmark" href="#top" aria-label="Alex Morgan home">AM<span>.</span></a><nav className="site-nav" aria-label="Primary navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-availability" href="mailto:alex.morgan@example.com"><span /> Available for work</a></header>
      <section className="hero section-frame" id="top"><div className="hero-copy"><p className="eyebrow">Software engineer · New York / Remote</p><h1>IT systems that <em>make work clearer.</em></h1><p className="hero-summary">I build dependable web products for teams with real work to do — from the first useful screen to the details that make people trust the whole system.</p><div className="hero-actions"><a className="primary-link" href="#work">View selected work <ArrowDownRight size={17} /></a><a className="text-link" href="/resume.txt" download="alex-morgan-resume.txt">Download résumé <Download size={16} /></a></div></div><div className="hero-proof" aria-label="Profile summary"><div className="proof-mark"><Terminal size={22} /></div><p className="proof-label">Currently focused on</p><p className="proof-title">Tools people<br />can trust.</p><p className="proof-detail">Product-minded engineering, thoughtful interfaces, and practical outcomes.</p><div className="proof-footer"><span>01</span><span>Profile / 2026</span></div></div></section>
      <section className="signal-strip" aria-label="Career snapshot"><div><span className="signal-number">6+</span><span>years building for the web</span></div><div><span className="signal-number">24</span><span>projects shipped with care</span></div><div><span className="signal-number">100%</span><span>curiosity about the hard parts</span></div></section>
      <section className="section-frame work-section" id="work"><div className="section-heading"><div><p className="eyebrow">Selected work</p><h2>A few things I&apos;ve made useful.</h2></div><p className="section-aside">A short list of product work, systems thinking, and one game.</p></div><div className="project-grid">{projects.map((project) => <article className={`project-card ${project.tone}`} key={project.number}><div className="project-card-top"><span>{project.number}</span><ArrowUpRight size={19} /></div><div><h3>{project.title}</h3><p>{project.description}</p></div><div className="tag-row">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
      <section className="section-frame about-section" id="about"><div className="about-grid"><div><p className="eyebrow">A little context</p><h2>Good software should lower the temperature.</h2></div><div className="about-copy"><p>I like working where technology meets a messy human process. My role is usually part builder, part translator: turning an unclear need into a simple flow, then making the implementation sturdy enough to last.</p><p>That means I care about the whole shape of a product — what it says, how it feels, what happens when something goes wrong, and whether the person using it gets to go home on time.</p><a className="text-link" href="mailto:alex.morgan@example.com">Let&apos;s talk about your team <ArrowUpRight size={16} /></a></div></div><div className="skills-block"><p className="eyebrow">Tools I work with</p><div className="skills-list">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></section>
      <section className="section-frame endorsements-section" id="endorsements"><div className="section-heading"><div><p className="eyebrow">Endorsements</p><h2>Let the people you&apos;ve helped tell the story.</h2></div><p className="section-aside">A few words from the people who have seen the work up close.</p></div><div className="endorsement-grid">{endorsements.map((endorsement) => <blockquote className="endorsement-card" key={endorsement.name}><Quote size={22} className="quote-mark" /><p>“{endorsement.quote}”</p><footer><strong>{endorsement.name}</strong><span>{endorsement.role}</span></footer></blockquote>)}</div><div className="endorsement-note"><span className="endorsement-note-dot" /><p>These are placeholders for real recommendations. Replace them with approved quotes before sharing the portfolio.</p></div></section>
      <section className="section-frame game-section" id="game"><div className="game-intro"><p className="eyebrow">A small side project</p><h2>Proof that the details matter.</h2><p>The best interfaces feel obvious in use. This tiny game is a quick way to see how I think about state, feedback, input, and the little moments between.</p><a className="text-link" href="#contact">Want to see the code? <ArrowUpRight size={16} /></a></div><SnakeGame /></section>
      <section className="contact-section" id="contact"><div className="section-frame contact-inner"><div><p className="eyebrow">Open to the right next thing</p><h2>Have a useful problem?</h2><p className="contact-copy">I&apos;d like to hear what you&apos;re building and where it needs to get sharper.</p></div><div className="contact-actions"><a className="primary-link" href="mailto:alex.morgan@example.com"><Mail size={17} /> Send me an email</a><a className="contact-email" href="mailto:alex.morgan@example.com">alex.morgan@example.com <ArrowUpRight size={16} /></a><p className="location"><MapPin size={15} /> New York, available remotely</p></div></div></section>
      <footer className="site-footer section-frame"><span>© 2026 Alex Morgan</span><span>Built with care for the web.</span><a href="#top">Back to top <ArrowUpRight size={14} /></a></footer>
    </main>
  );
}
