import { ArrowDownRight, ArrowUpRight, Code2, Download, Mail, MapPin, Phone, Terminal } from "lucide-react";
import { SnakeGame } from "@/components/snake-game";

const projects = [
  { number: "01", title: "Portfolio personnel", description: "Je développe ce site afin d’apprendre les bases du développement web, de l’organisation d’une interface et de la présentation d’un projet.", objective: "Créer un site clair pour présenter mon parcours et mes projets.", learned: "HTML · CSS · JavaScript · organisation d’un projet web", tags: ["HTML", "CSS", "JavaScript"], tone: "mint" },
  { number: "02", title: "Bot Discord", description: "Projet personnel autour de la création d’un bot Discord afin de découvrir la programmation, les commandes, les API et l’automatisation.", objective: "Comprendre comment un programme peut réagir à des commandes et communiquer avec un service externe.", learned: "Programmation · API · logique · automatisation", tags: ["Bot", "API", "Logique"], tone: "sand" },
  { number: "03", title: "Projets Python", description: "Plusieurs petits programmes réalisés pour apprendre progressivement la programmation et mettre en pratique les notions découvertes.", objective: "Tester différentes idées et transformer chaque notion en exercice concret.", learned: "Python · logique · fonctions · fichiers", tags: ["Python", "Fonctions", "Fichiers"], tone: "blue" },
  { number: "04", title: "Linux & réseaux", description: "Expérimentations personnelles autour de Linux, des systèmes et des bases des réseaux informatiques. Je documente progressivement ce que j’apprends.", objective: "Mieux comprendre les systèmes et le fonctionnement d’un réseau.", learned: "Linux · systèmes · réseau · machines virtuelles", tags: ["Linux", "Systèmes", "Réseaux"], tone: "mint" },
  { number: "05", title: "Programmation Roblox", description: "Ma première expérience avec la programmation est notamment passée par Roblox Studio. J’y ai découvert la logique de programmation et la création de scripts avec Luau.", objective: "Découvrir la programmation à travers la création de jeux et d’interactions.", learned: "Luau · logique · scripts · création de jeux", tags: ["Luau", "Scripts", "Roblox"], tone: "sand" },
];
const learningTopics = [
  { title: "Python", stage: "Débutant", detail: "En progression" },
  { title: "HTML / CSS", stage: "Bases", detail: "En progression" },
  { title: "JavaScript", stage: "Découverte", detail: "En progression" },
  { title: "Linux", stage: "Découverte", detail: "En progression" },
  { title: "Réseaux", stage: "Découverte", detail: "En progression" },
  { title: "Luau", stage: "Bases", detail: "En progression" },
];

export default function Home() {
  return (
    <main>
      <header className="site-header"><a className="wordmark" href="#accueil" aria-label="Accueil du portfolio de Roméo Paris">RP<span>.</span></a><nav className="site-nav" aria-label="Navigation principale"><a href="#accueil">Accueil</a><a href="#projets">Projets</a><a href="#parcours">Parcours</a><a href="#competences">Compétences</a><a href="#apropos">À propos</a><a href="#contact">Contact</a></nav><a className="header-cv" href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf">CV <Download size={14} /></a></header>
      <section className="hero section-frame" id="accueil"><div className="hero-copy"><p className="eyebrow">Futur apprenti informaticien · 16 ans · Bulle, Fribourg</p><h1>J’apprends. <em>Je construis. Je progresse.</em></h1><p className="hero-summary">Passionné par l’informatique, je développe mes compétences à travers des projets personnels et mes différentes expériences. Mon objectif est d’intégrer un <strong>CFC d’informaticien en septembre 2027</strong> et de continuer à apprendre dans un environnement professionnel.</p><div className="hero-actions"><a className="primary-link" href="#projets">Voir mes projets <ArrowDownRight size={17} /></a><a className="text-link" href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf">Télécharger mon CV <Download size={16} /></a><a className="text-link" href="#contact">Me contacter <ArrowUpRight size={16} /></a></div></div><div className="hero-proof" aria-label="Objectif professionnel"><div className="proof-mark"><Terminal size={22} /></div><p className="proof-label">Objectif professionnel</p><p className="proof-title">CFC Informatique<br />Septembre 2027</p><p className="proof-detail">Je cherche une place d’apprentissage, un stage ou une journée de découverte dans la région de Fribourg et alentours.</p><div className="proof-footer"><span>16 ans</span><span>Bulle · Suisse</span></div></div></section>
      <section className="signal-strip" aria-label="Résumé du profil"><div><span className="signal-number">16 ans</span><span>curieux et motivé</span></div><div><span className="signal-number">2027</span><span>objectif : CFC Informatique</span></div><div><span className="signal-number">💻</span><span>projets personnels</span></div></section>
      <section className="section-frame focus-section" id="recherche"><div className="about-grid"><div><p className="eyebrow">Ce que je recherche</p><h2>Je recherche une place d’apprentissage.</h2></div><div className="about-copy"><p>Je recherche une <strong>place d’apprentissage CFC d’informaticien pour septembre 2027</strong> dans la région de Fribourg et alentours. Je suis également intéressé par les stages et les journées de découverte permettant de mieux connaître le métier.</p><div className="interest-grid"><span>💻 Développement d’applications</span><span>🖥️ Systèmes et informatique</span><span>🌐 Réseaux</span><span>🛠️ Support informatique</span><span>🤖 Automatisation</span><span>📚 Nouvelles technologies</span></div><p><strong>Je suis ouvert à découvrir différents domaines de l’informatique afin de trouver celui qui me correspond le mieux.</strong></p></div></div></section>
      <section className="section-frame work-section" id="projets"><div className="section-heading"><div><p className="eyebrow">Mes projets personnels</p><h2>J’apprends en construisant.</h2></div><p className="section-aside">Des projets d’apprentissage, présentés honnêtement et progressivement.</p></div><div className="project-grid">{projects.map((project) => <article className={`project-card ${project.tone}`} key={project.number}><div className="project-card-top"><span>{project.number}</span><ArrowUpRight size={19} /></div><div><h3>{project.title}</h3><p>{project.description}</p><div className="project-detail"><strong>Objectif</strong><span>{project.objective}</span></div><div className="project-detail"><strong>Ce que j’apprends</strong><span>{project.learned}</span></div></div><div className="tag-row">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
      <section className="section-frame learning-section" id="competences"><div className="section-heading"><div><p className="eyebrow">En apprentissage</p><h2>Je progresse étape par étape.</h2></div><p className="section-aside">Des niveaux réalistes, sans fausses barres de progression.</p></div><div className="learning-grid">{learningTopics.map((topic, index) => <article className="learning-card" key={topic.title}><p className="learning-number">0{index + 1}</p><h3>{topic.title}</h3><div className="learning-stage"><span>{topic.stage}</span><span>{topic.detail}</span></div></article>)}</div></section>
      <section className="section-frame about-section" id="parcours"><div className="about-grid"><div><p className="eyebrow">Mon parcours</p><h2>Mes expériences m’ont permis de découvrir le monde professionnel.</h2></div><div className="about-copy"><h3>Formation professionnelle — Électronique</h3><p>J’ai commencé une formation professionnelle dans le domaine de l’électronique. Cette expérience m’a permis de découvrir le fonctionnement d’une formation professionnelle, le monde du travail, le travail en équipe ainsi que l’importance de la précision et de la rigueur.</p><p>Après cette expérience, j’ai choisi de réorienter mon projet professionnel vers l’informatique.</p><h3>Stage — HFR Fribourg</h3><p>Première expérience dans le monde professionnel, qui m’a permis de découvrir un environnement de travail et de développer mon sens de l’organisation et des responsabilités.</p><h3>FutureKids Fribourg</h3><p>Première découverte de la programmation et de la création numérique, qui a renforcé mon intérêt pour l’informatique.</p></div></div></section>
      <section className="section-frame motivation-section"><div className="motivation-card"><p className="eyebrow">Pourquoi l’informatique ?</p><h2>Partir d’une idée et chercher une solution concrète.</h2><p>Ce qui me plaît dans l’informatique, c’est de pouvoir partir d’un problème ou d’une idée et chercher une solution concrète.</p><p>J’aime expérimenter, comprendre comment les choses fonctionnent et apprendre de mes erreurs. Mes projets personnels me permettent de découvrir progressivement différents domaines de l’informatique et de mieux comprendre dans quelle direction je souhaite évoluer.</p></div></section>
      <section className="section-frame about-section about-profile" id="apropos"><div className="about-grid"><div><p className="eyebrow">À propos de moi</p><h2>Qui suis-je ?</h2></div><div className="about-copy"><p>Je suis quelqu’un de curieux, sociable et persévérant. Lorsque quelque chose m’intéresse, j’aime chercher par moi-même, expérimenter et comprendre pourquoi une solution fonctionne.</p><p>Je suis encore au début de mon parcours informatique et je ne prétends pas tout connaître. Je cherche justement une formation qui me permettra d’apprendre, de progresser et de transformer progressivement ma passion en compétences professionnelles.</p></div></div></section>
      <section className="section-frame github-section" id="github"><div className="github-card"><div><p className="eyebrow">Mon GitHub</p><h2>Mes projets et mon évolution.</h2><p>Je publie progressivement mes projets personnels et mes expérimentations afin de garder une trace de mon apprentissage et de montrer concrètement ce que je réalise.</p></div><a className="github-action github-link" href="https://github.com/Romeostart" target="_blank" rel="noreferrer"><Code2 size={28} /><span className="text-link">Voir mon GitHub <ArrowUpRight size={16} /></span><small>github.com/Romeostart</small></a></div></section>
      <section className="section-frame cv-section" id="cv"><div className="cv-card"><div><p className="eyebrow">CV</p><h2>Vous souhaitez en savoir plus sur mon parcours ?</h2></div><a className="primary-link" href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf">Télécharger mon CV <Download size={17} /></a></div></section>
      <section className="section-frame game-section" id="jeu"><div className="game-intro"><p className="eyebrow">Une petite démonstration</p><h2>Un projet d’apprentissage interactif.</h2><p>J’ai ajouté ce petit jeu pour rendre mon portfolio interactif et montrer une première approche de la logique de programmation.</p><p className="project-status">Projet d’apprentissage</p><span className="text-link text-link-disabled">Code bientôt disponible <ArrowUpRight size={16} /></span></div><SnakeGame /></section>
      <section className="contact-section" id="contact"><div className="section-frame contact-inner"><div><p className="eyebrow">Contact</p><h2>Parlons de mon futur apprentissage.</h2><p className="contact-copy">Vous êtes à la recherche d’un apprenti informaticien pour septembre 2027 ? Je serais heureux de pouvoir échanger avec vous et de vous présenter mon parcours et mes projets.</p></div><div className="contact-actions"><a className="primary-link" href="mailto:Romeo.paris321@gmail.com"><Mail size={17} /> Me contacter par e-mail</a><a className="text-link contact-download" href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf"><Download size={16} /> Télécharger mon CV</a><a className="contact-email" href="mailto:Romeo.paris321@gmail.com">Romeo.paris321@gmail.com <ArrowUpRight size={16} /></a><a className="contact-email" href="tel:+41766151828"><Phone size={16} /> +41 76 615 18 28</a><p className="location"><MapPin size={15} /> Bulle · Fribourg · Suisse</p></div></div></section>
      <footer className="site-footer section-frame"><div><strong>Roméo Paris</strong><span>Futur apprenti informaticien · CFC 2027</span><span>Bulle · Fribourg · Suisse</span></div><div><a href="mailto:Romeo.paris321@gmail.com">E-mail</a><a href="https://github.com/Romeostart" target="_blank" rel="noreferrer">GitHub</a><a href="/CV-Romeo-Paris.pdf" download="CV-Romeo-Paris.pdf">CV</a></div><span>© 2026 Roméo Paris</span></footer>
    </main>
  );
}
